In [ ]:
import numpy as np 

In [15]:
# 2. Print the numpy version and the configuration (★☆☆)
# version
np.__version__ 

'1.20.3'

In [13]:
# configuration
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dell/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Dell/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dell/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Dell/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dell/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Dell/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dell/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Dell/anaconda3\\Library\\include']


In [9]:
#3. Create a null vector of size 10 (★☆☆)

np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
# 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

z=np.arange(1,10)
z[5]=1
z 

array([1, 2, 3, 4, 5, 1, 7, 8, 9])

In [21]:
# 7. Create a vector with values ranging from 10 to 49 (★☆☆)
np.arange(10,50)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [35]:
# 8. Reverse a vector (first element becomes last) (★☆☆)

z[::-1]

array([9, 8, 7, 1, 5, 4, 3, 2, 1])

In [24]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

np.arange(0,9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [37]:
# 11. Create a 3x3 identity matrix (★☆☆)

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
# 12. Create a 3x3x3 array with random values (★☆☆)

np.random.random([3,3,3])

array([[[0.16312034, 0.3025141 , 0.14900162],
        [0.82111446, 0.71811706, 0.60460504],
        [0.78330954, 0.12080574, 0.11386764]],

       [[0.35991165, 0.06555873, 0.36693886],
        [0.84353293, 0.04385556, 0.31703636],
        [0.72293065, 0.09929702, 0.5681151 ]],

       [[0.84078732, 0.33419803, 0.58652137],
        [0.98837275, 0.59988112, 0.99935525],
        [0.50759389, 0.15896837, 0.79750703]]])

In [50]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

random_values = np.random.random([10,10])
print(np.min(random_values))
np.max(random_values)


0.031654967354492025


0.992587478264658

In [52]:
# 14. Create a random vector of size 30 and find the mean value (★☆☆)

size = np.random.random([30])
np.mean(size)


0.590764569773704

In [62]:
# 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# 16. How to add a border (filled with 0's) around an existing array? (★☆☆)





In [ ]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)




In [ ]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)




In [ ]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)




In [ ]:
# 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)




In [ ]:
# 22. Normalize a 5x5 random matrix (★☆☆)


In [ ]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)


In [ ]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)


In [ ]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)


In [ ]:
# 26. What is the output of the following script? (★☆☆)
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [ ]:
# 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z 



In [ ]:
# 29. How to round away from zero a float array ? (★☆☆)


In [ ]:
# 30. How to find common values between two arrays? (★☆☆)


In [ ]:
# 31. How to ignore all numpy warnings (not recommended)? (★☆☆)


In [ ]:
# 32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

In [65]:
# 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

np.datetime_data()

TypeError: datetime_data() takes exactly 1 argument (0 given)

In [ ]:
 # 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

    
    

In [ ]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)


In [ ]:
# 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)


In [ ]:
 # 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)


In [ ]:
# 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)


In [ ]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)


In [ ]:
# 40. Create a random vector of size 10 and sort it (★★☆)


In [ ]:
 # 41. How to sum a small array faster than np.sum? (★★☆)
