In [ ]:
#pip install numpy

In [1]:
import numpy as np

In [2]:
#1 Dimensional Array
a=np.array([4,7,8,5,4,5,5,9])

In [3]:
a

array([4, 7, 8, 5, 4, 5, 5, 9])

In [4]:
#It is an ndarray, i.e. n-dimensional array
type(a)

numpy.ndarray

In [5]:
a.shape

(8,)

In [5]:
#2 Dimensional Array
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
a.shape

(3, 2)

In [12]:
a=np.array([[1,2,8,6],[9,10,3,4],[5,6,6,2]])
a

array([[ 1,  2,  8,  6],
       [ 9, 10,  3,  4],
       [ 5,  6,  6,  2]])

In [8]:
a.shape

(3, 4)

In [13]:
a[1,1]

10

In [10]:
a[2,3]

2

In [11]:
a[2,0]

5

In [14]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [15]:
a=np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [16]:
a=np.arange(5,12)
a

array([ 5,  6,  7,  8,  9, 10, 11])

In [17]:
a=np.arange(3,50,5)
a

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [18]:
16,15,14....6,5,4,3,2,1
a=np.arange(16,2,-3)
a

array([16, 13, 10,  7,  4])

Create a dataframe using numpy array structure, with 3 columns,

1st col- squares of 1st 10 natural numbers

2nd col- cubes of 1st 10 natural numbers

3rd col- mean of the 1st 2 columns

In [20]:
a1=np.arange(1,11)
a1=a1*a1
a2=np.arange(1,11)
a2=a2**3
a3=(a1+a2)/2
a3
import pandas as pd 
df=pd.DataFrame(columns=['a1','a2','a3'])
df['a1']=pd.Series(a1)
df['a2']=pd.Series(a2)
df['a3']=pd.Series(a3)
df

a1    a2     a3
0    1     1    1.0
1    4     8    6.0
2    9    27   18.0
3   16    64   40.0
4   25   125   75.0
5   36   216  126.0
6   49   343  196.0
7   64   512  288.0
8   81   729  405.0
9  100  1000  550.0

In [23]:
import pandas as pd
df=pd.DataFrame(columns=['Squares', 'Cubes', 'Mean'])
df['Squares']=pd.Series(np.arange(1,11)**2)
df['Cubes']=pd.Series(np.arange(1,11)**3)
df['Mean']=pd.Series(((np.arange(1,11)**2)+(np.arange(1,11)**3))/2)
df


Squares  Cubes   Mean
0        1      1    1.0
1        4      8    6.0
2        9     27   18.0
3       16     64   40.0
4       25    125   75.0
5       36    216  126.0
6       49    343  196.0
7       64    512  288.0
8       81    729  405.0
9      100   1000  550.0

In [21]:
import pandas as pd
a=np.arange(1,11)
print(a)
b=[]
for i in a:
    b.append(i*i)
print(b)
x=pd.Series(b)    
x

[ 1  2  3  4  5  6  7  8  9 10]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


0      1
1      4
2      9
3     16
4     25
5     36
6     49
7     64
8     81
9    100
dtype: int64

In [24]:
a=np.arange(1,11)
b=[]
for i in a:
    b.append(i*i*i)
y=pd.Series(b)    
y  

0       1
1       8
2      27
3      64
4     125
5     216
6     343
7     512
8     729
9    1000
dtype: int64

In [25]:
z=(x+y)/2
z

0      1.0
1      6.0
2     18.0
3     40.0
4     75.0
5    126.0
6    196.0
7    288.0
8    405.0
9    550.0
dtype: float64

In [26]:
frame={'x':x, 'y':y, "z":z }
result=pd.DataFrame(frame)
result

x     y      z
0    1     1    1.0
1    4     8    6.0
2    9    27   18.0
3   16    64   40.0
4   25   125   75.0
5   36   216  126.0
6   49   343  196.0
7   64   512  288.0
8   81   729  405.0
9  100  1000  550.0

In [ ]:
a=([[0,11]])
for a in range(1,11):
    print(a*a*a, end= ",")

In [ ]:
a = np.arange(0,11)
a*a*a

In [27]:
#linspace
a=np.linspace(2,16,6)
a

#2 , , , , , 16

array([ 2. ,  4.8,  7.6, 10.4, 13.2, 16. ])

In [28]:
a=np.linspace(2,20,9)
a

#2..........20

array([ 2.  ,  4.25,  6.5 ,  8.75, 11.  , 13.25, 15.5 , 17.75, 20.  ])

In [29]:
b=np.zeros(8)
b

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
#5 is the number of times array is repeated
#3 is the number of rows per array
#4 is the number of columns per array
c=np.zeros((5,3,4))
c

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [39]:
a=np.array([[8,7,5],[10,3,9],[2,8,4]])
a

array([[ 8,  7,  5],
       [10,  3,  9],
       [ 2,  8,  4]])

In [40]:
a[:,1]

array([7, 3, 8])

In [41]:
a[2,:]

array([2, 8, 4])

In [42]:
#Axis 0 = Column-wise
#Axis 1 = Row-wise

In [43]:
a.max(axis=0)

array([10,  8,  9])

In [44]:
a.max(axis=1)

array([ 8, 10,  8])

In [45]:
a.min(axis=0)

array([2, 3, 4])

In [46]:
a = np.array([[2,3,3,4],[3,4,4,4],[5,6,2,3],[7,8,4,4]])
print(a)

[[2 3 3 4]
 [3 4 4 4]
 [5 6 2 3]
 [7 8 4 4]]


In [47]:
#Column-wise sum values
a.sum(axis=0)

array([17, 21, 13, 15])

In [48]:
# Row-wise sum values
a.sum(axis=1)

array([12, 15, 16, 23])

In [64]:
#Square Root the entire array
a=np.array([[2,1,5],[8,3,9]])
print(a)
np.sqrt(a)

[[2 1 5]
 [8 3 9]]


array([[1.41421356, 1.        , 2.23606798],
       [2.82842712, 1.73205081, 3.        ]])

In [51]:
#To find square root of a specific element, e.g. 8
print(a)
print(a[1,0])
np.sqrt(a[1,0])

[[2 1 5]
 [8 3 9]]
8


2.8284271247461903

In [52]:
#To find square root of entire row 2
print(a)
np.sqrt(a[1,:])

[[2 1 5]
 [8 3 9]]


array([2.82842712, 1.73205081, 3.        ])

In [65]:
#To find square root of entire column 1
print(a)
np.sqrt(a[:,0])

[[2 1 5]
 [8 3 9]]


array([1.41421356, 2.82842712])

In [53]:
np.log(a)

array([[0.69314718, 0.        , 1.60943791],
       [2.07944154, 1.09861229, 2.19722458]])

Log of a number to a base defined will give us the number to which the base must be raised to get the value for which we are finding the log 

Log of 'a' to the base 'b' will give us the power of 'b', for which the result will be 'a' 
log of 4 to the base 2

### Natural log

log of 5 will give us the power of e (constant) which gives the output as 5. 

e=2.718

In [ ]:
a = np.array([[2,3,3,4],[3,4,4,4],[5,6,2,3],[7,8,4,4]])
print(a)
np.square(a)

In [ ]:
np.cumsum(a)

In [57]:
a = np.arange(51)
print(a)
np.cumsum(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


array([   0,    1,    3,    6,   10,   15,   21,   28,   36,   45,   55,
         66,   78,   91,  105,  120,  136,  153,  171,  190,  210,  231,
        253,  276,  300,  325,  351,  378,  406,  435,  465,  496,  528,
        561,  595,  630,  666,  703,  741,  780,  820,  861,  903,  946,
        990, 1035, 1081, 1128, 1176, 1225, 1275], dtype=int32)

In [54]:
a = np.arange(0,50.5,.5)
print(a)
np.cumsum(a)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5 30.  30.5 31.  31.5 32.  32.5 33.  33.5 34.  34.5
 35.  35.5 36.  36.5 37.  37.5 38.  38.5 39.  39.5 40.  40.5 41.  41.5
 42.  42.5 43.  43.5 44.  44.5 45.  45.5 46.  46.5 47.  47.5 48.  48.5
 49.  49.5 50. ]


array([0.0000e+00, 5.0000e-01, 1.5000e+00, 3.0000e+00, 5.0000e+00,
       7.5000e+00, 1.0500e+01, 1.4000e+01, 1.8000e+01, 2.2500e+01,
       2.7500e+01, 3.3000e+01, 3.9000e+01, 4.5500e+01, 5.2500e+01,
       6.0000e+01, 6.8000e+01, 7.6500e+01, 8.5500e+01, 9.5000e+01,
       1.0500e+02, 1.1550e+02, 1.2650e+02, 1.3800e+02, 1.5000e+02,
       1.6250e+02, 1.7550e+02, 1.8900e+02, 2.0300e+02, 2.1750e+02,
       2.3250e+02, 2.4800e+02, 2.6400e+02, 2.8050e+02, 2.9750e+02,
       3.1500e+02, 3.3300e+02, 3.5150e+02, 3.7050e+02, 3.9000e+02,
       4.1000e+02, 4.3050e+02, 4.5150e+02, 4.7300e+02, 4.9500e+02,
       5.1750e+02, 5.4050e+02, 5.6400e+02, 5.8800e+02, 6.1250e+02,
       6.3750e+02, 6.6300e+02, 6.8900e+02, 7.1550e+02, 7.4250e+02,
       7.7000e+02, 7.9800e+02, 8.2650e+02, 8.5550e+02, 8.8500e+02,
       9.1500e+02, 9.4550e+02, 9.7650e+02, 1.0080e+03, 1.0400e+03,
       1.0725e+03, 1.1055e+03, 1.1390e+03, 1.1730e+03, 1.2075e+03,
       1.2425e+03, 1.2780e+03, 1.3140e+03, 1.3505e+03, 1.3875e

In [62]:
a=np.array([[1,5,3],[6,2,4]])
b=np.array([[8,5,7],[4,3,1]])
print(a)
print(b)
a+b

[[1 5 3]
 [6 2 4]]
[[8 5 7]
 [4 3 1]]


array([[ 9, 10, 10],
       [10,  5,  5]])

In [63]:
#What if we try to add arrays with different dimensions i.e. unequal number of rows/columns?
a=np.array([[1,5,3],[6,2,4],[7,8,9]])
b=np.array([[8,5,7],[4,3,1]])
print(a)
print(b)
a+b

[[1 5 3]
 [6 2 4]
 [7 8 9]]
[[8 5 7]
 [4 3 1]]


ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [ ]:
a=np.array([[1,5,3],[6,2,4]])
b=np.array([[8,5,7],[4,3,1]])

print(a)
print(b)
a-b

In [ ]:
print(a)
print(b)
a*b

In [ ]:
print(a)
print(b)
a/b

In [ ]:
print(a)
print(b)

In [66]:
a=np.array([[1,5,3],[6,2,4]])
b=np.array([[8,5,7],[4,3,1]])
print(a)
print(b)

[[1 5 3]
 [6 2 4]]
[[8 5 7]
 [4 3 1]]


For a vertical stack, i.e. placing the array elements of a & b one below the other, we must have equal number of columns in both the arrays to be stacked

In [67]:
np.vstack((a,b))

array([[1, 5, 3],
       [6, 2, 4],
       [8, 5, 7],
       [4, 3, 1]])

For a horizontal stack, i.e. placing the array elements of a & b next to each other, we must have equal number of rows in both the arrays to be stacked

In [68]:
np.hstack((a,b))

array([[1, 5, 3, 8, 5, 7],
       [6, 2, 4, 4, 3, 1]])

In [69]:
a=np.array([[1,5,3],[6,2,4]])
b=np.array([[8,5,8,6],[4,3,7,9]])
print(a)
print(b)

[[1 5 3]
 [6 2 4]]
[[8 5 8 6]
 [4 3 7 9]]


In [70]:
np.vstack((a,b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [71]:
np.hstack((a,b))

array([[1, 5, 3, 8, 5, 8, 6],
       [6, 2, 4, 4, 3, 7, 9]])

In [ ]:
array1=np.arange(15).reshape(3,5)
array1

In [ ]:
array1=np.arange(30).reshape(5,6)
array1

In [ ]:
array1[3][2]=14
array1

In [ ]:
a=np.array([[4,8,7,5,6,1,4,8,7,4]])
b=np.unique(a)
b

In [ ]:
import numpy as np
a=np.array([[4,8,7,5,6],[1,4,8,7,4]])
a

In [ ]:
b=a.transpose()
b

In [ ]:
a=np.array([2,5,4,6,7,8])
b=np.array([4,7,8,5,4,4])
print(a)
print(b)

In [ ]:
c=np.concatenate((a,b))
c

In [ ]:
c=np.concatenate((b,a))
c

In [ ]:
a=np.array([[2,5,4],[6,7,8]])
b=np.array([[4,7,8],[5,4,4]])

In [ ]:
print(a)
print(b)

In [ ]:
c=np.concatenate((a,b))
c

In [ ]:
help(np.allclose)

In [ ]:
import numpy as np
Array1=np.linspace(3,5,5)
print(Array1)
Array2=np.linspace(4,5,5)
print(Array2)
np.greater_equal(Array1,Array2)

In [ ]:
np.

In [ ]:
np.equal(Array1,Array2)

In [ ]:
Array1=np.linspace(3,6,5)
print(Array1)
Array2=np.linspace(4,9,5)
print(Array2)
np.greater_equal(Array1,Array2)

In [ ]:
Array1=np.empty((3,2),dtype=int)
Array1

In [ ]:
Array1=np.ones((3,6),dtype=int)
Array1

In [ ]:
l=[1,5,7,5,5,7,4]
arr=np.asarray(l)
arr

In [ ]:
l=[1,5,[7,5],5,7,4]
arr=np.asarray(l)
arr

In [ ]:
type(arr)

In [ ]:
l=(4,7,8,5,1,4,6)
arr=np.asarray(l)
arr

In [ ]:
type(arr)

In [ ]:
Dict_1 = {d: "ABC", e : "DEF" , f: "GHI"}
Dict_1

In [ ]:
a=np.array([4,5,2,1,7,8,6,3,4,5])
b=np.array([8,5,4,1,3,9,8,5,2,1])
c=a*b
c

In [ ]:
d=a+b
d

In [ ]:
a=np.array([4,5,2,1,7,8,6,3,4])
b=np.array([8,5,4,1,3,9,8,5,2,1])
c=a+b
c

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[4,7,2,1]])
b=np.array([4,7,8,5])
c=a+b
c

In [ ]:
a=np.array([[1,2,3,5],[5,8,9,7],[8,2,4,6]])
a

In [ ]:
for x in np.nditer(a):
    print(x,end=' ')

In [ ]:
for x in np.nditer(a):
    print(x)

In [ ]:
print(a)

In [ ]:
# 'T' stands for transpose... It will change rows to columns & columns to rows.
trans_a=a.T
trans_a

In [ ]:
np.char.add(['Welcome','to'],['Python','Session'])

In [ ]:
np.add([2,3],[5,8])

In [ ]:
np.char.multiply("Hello",5)

In [ ]:
print(np.char.center('Python Session',30,'+'))
np.char.center('Python Session',30,'+')

In [ ]:
np.char.capitalize('welcome to python session')          

In [ ]:
np.char.title('welcome to python session')

In [ ]:
np.char.upper('welcome to python session')

In [ ]:
np.char.lower('WELCOME TO PYTHON SESSION')

In [ ]:
np.char.split("Welcome to Python Session")

In [ ]:
print(np.char.splitlines("Welcome\nto\nPython\nSession"))

In [ ]:
print(np.char.strip("        Welcome\nto\nPython\nSession     "))

In [ ]:
print(np.char.join('-','HMNSGD'))

In [ ]:
s='Welcome to Python Session'
s

In [ ]:
import numpy as np

In [ ]:
print(s)
print(np.char.replace(s,"Welcome to ","www."))

In [ ]:
t='Hello Neha, welcome to the class'
print(t)
print(np.char.replace(t,"class","party"))

In [ ]:
arr = np.array([12.2021, 90.23120, 123.0203, 23.202])
np.around(arr, 2)

In [ ]:
arr=np.array([12.45158,45.786546,7.8415868,5.486,4.8])
np.around(arr,3)

In [ ]:
np.floor(arr)

In [ ]:
np.ceil(arr)

In [ ]:
a = np.array([[2,10,20],[80,43,31],[22,43,10]])
np.amin(a)
np.amin(a)
np.amin(a,0)
np.amax(a,0)
np.amin(a,1)
np.amax(a,1)

In [ ]:
a=np.array([[2,10,20],[80,43,31],[22,43,10]])
a

In [ ]:
np.amax(a,1)

In [ ]:
np.ptp(a,1)
np.ptp(a,0)


In [ ]:
#Peak to peak

In [ ]:
a

In [ ]:
np.ptp(a,1)

In [ ]:
a=np.array([[1,4],[5,3]])
a

In [ ]:
np.sum(a,axis=1)

In [ ]:
a=np.random.rand(5,2)
a

In [ ]:
a=np.random.randint(5, size=(5,6))
a

In [ ]:
np.array([1.+0.j, 2.+0.j, 3.+0.j],dtype=float)

In [ ]:
np.mat(np.array([1,2,3,4]))

In [ ]:
np.mat(np.array([[1,4,5],[7,8,9]]))

In [ ]:
np.mat('1 2;3 4;8 9')

In [ ]:
a=[7,4,5,6,9]
type(a)

In [ ]:
type(np.asarray(a))

In [ ]:
type(a)

In [ ]:
issubclass(np.matrix,np.ndarray)

In [ ]:
issubclass(np.ndarray,np.matrix)

In [ ]:
a=[1,2,3]
type(a)

In [ ]:
np.asanyarray(a)

In [ ]:
a=np.matrix([1,2,3,4])
a

In [ ]:
np.asanyarray(a)

In [ ]:
x=np.array([1,2,3])
x

In [ ]:
y=x

In [ ]:
y

In [ ]:
y[1]=45

In [ ]:
y

In [ ]:
x

In [ ]:
x[0]=89
x

In [ ]:
y

In [ ]:
x=[1,2,3]
x

In [ ]:
z=np.copy(x)
z

In [ ]:
x[2]=8435486
x

In [ ]:
z

In [ ]:
z[2]=89
z

In [ ]:
x

In [ ]:
np.fromfunction(lambda i,j: i==j,(3,3),dtype=int)

In [ ]:
i=np.mat(np.array([[0,0,0],[1,1,1],[2,2,2]]))
i

In [ ]:
j=np.mat(np.array([[0,1,2],[0,1,2],[0,1,2]]))
j

In [ ]:
print(i)
print(j)
k=np.array([['00','01','02'],['10','11','12'],['20','21','22']])
print(k)

In [ ]:
np.fromfunction(lambda i,j: i*j,(3,3),dtype=int)

In [ ]:
np.fromfunction(lambda i,j,k: i*j*k,(3,3,3),dtype=int)

In [ ]:
list(range(5))
iterable=(x*x for x in range(5))

In [ ]:
iterable

In [ ]:
np.fromiter(iterable,float)

In [ ]:
list(range(5))

Create a list of a few temperature values in celcius (between 30 to 45 degrees)
Using 'for' loop, create another list where the celcius temperatures are converted into fahrenheit.

C*(9/5)+32=F

After converting to fahrenheit, create a dataframe with one column showing the above temperatures in celcius,and the nect column showing fahrenheit values for the given temperatures.

In [ ]:
import numpy as np
import pandas as pd
C=np.arange(30,45,2)
print(C)
F=[]
for i in (C,F):
    F=C*(9/5)+32
    
print(F)

TEMPERATURE={"C":C, "F":F}
result=pd.DataFrame(TEMPERATURE)
result

In [ ]:
import pandas as pd
import numpy as np
import random 
df = pd.DataFrame(columns=['C','F'])
x=list(np.random.randint(30,45, size=(5)))
y=[]
for i in x:
    f=i*(9/5)+32
    y.append(f)
df['C']=pd.Series(x)
df['F']=pd.Series(y)
df

In [ ]:
a=np.random.randint(2,40,size=(5))
print(a)
b=np.linspace(6,9,2)
print(b)
np.less_equal(a,b)